apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: l2-network
  namespace: vm-test
spec:
  config: |2
    {
            "cniVersion": "0.3.1", 
            "name": "vm-test-l2-network", 
            "type": "ovn-k8s-cni-overlay", 
            "topology":"layer2", 
            "mtu": 1300, 
            "netAttachDefName": "vm-test/l2-network" 
    }