apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: rhel9-dual-nic-a
  namespace: vm-test
  labels:
    app: rhel9-dual-nic-a
spec:
  running: true
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: rhel9-dual-nic-a
      spec:
        sourceRef:
          kind: DataSource
          name: rhel9
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: rhel9
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: rhel9-dual-nic-a
        kubevirt.io/size: small
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - name: default
              masquerade: {}
            - name: secondary 
              bridge: {}
        machine:
          type: pc-q35-rhel9.2.0
        memory:
          guest: 2Gi
      networks:
        - name: default
          pod: {}
        - name: secondary
          multus:
            networkName: l2-network
      volumes:
        - dataVolume:
            name: rhel9-dual-nic-a
          name: rootdisk
        - cloudInitConfigDrive:
            userData: |-
              #cloud-config
              user: cloud-user
              password: fqkx-eivh-6axq
              chpasswd: { expire: False }
          name: cloudinitdisk

---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: rhel9-dual-nic-b
  namespace: vm-test
  labels:
    app: rhel9-dual-nic-b
spec:
  running: true
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: rhel9-dual-nic-b
      spec:
        sourceRef:
          kind: DataSource
          name: rhel9
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: rhel9
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: rhel9-dual-nic-b
        kubevirt.io/size: small
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - name: default
              masquerade: {}
            - name: secondary 
              bridge: {}
        machine:
          type: pc-q35-rhel9.2.0
        memory:
          guest: 2Gi
      networks:
        - name: default
          pod: {}
        - name: secondary
          multus:
            networkName: l2-network
      volumes:
        - dataVolume:
            name: rhel9-dual-nic-b
          name: rootdisk
        - cloudInitConfigDrive:
            userData: |-
              #cloud-config
              user: cloud-user
              password: fqkx-eivh-6axq
              chpasswd: { expire: False }
          name: cloudinitdisk